modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="beasts" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Beasts: Resurfaced" #mandatory
credits="Coda, VakyPanda, CircleF1sh" #optional
description='''Placeholder description.'''